### ISSUE TITLE
Non-existent reference to GIT SHA-1 of drat-trim

### ISSUE THREAD

**Issue by msoos** [aws-samples/aws-batch-hordesat-sample#10]
While doing `./makehordesat.sh`:

```
gcc -Wall -O3 -DNDBLSCR -DNLGLOG -DNDEBUG -DNCHKSOL -DNLGLPICOSAT -DNLGLDRUPLIG -DNLGLYALSAT -c lglmain.c
gcc -Wall -O3 -DNDBLSCR -DNLGLOG -DNDEBUG -DNCHKSOL -DNLGLPICOSAT -DNLGLDRUPLIG -DNLGLYALSAT -o lingeling lglmain.o -L. -llgl -lm
make: *** No rule to make target 'plingeling.c', needed by 'plingeling.o'.  Stop.
Cloning into '/home/soos/development/smt/smtcomp2020/aws-batch-hordesat-sample/hordesat/candy'...
Submodule path 'candy': checked out '9bf617b3f090af7f0e5b80548690af0a8b5b7149'
Submodule 'lib/drat-trim' (https://github.com/Udopia/drat-trim.git) registered for path 'lib/drat-trim'
Submodule 'test/googletest' (https://github.com/google/googletest.git) registered for path 'lib/googletest'
Submodule 'lib/minisat' (https://github.com/Udopia/minisat.git) registered for path 'lib/minisat'
Submodule 'lib/oscpack' (https://github.com/Udopia/oscpack.git) registered for path 'lib/oscpack'
Cloning into '/home/soos/development/smt/smtcomp2020/aws-batch-hordesat-sample/hordesat/candy/lib/drat-trim'...
Username for 'https://github.com':   
```

This is because candy is pointing to a non-existent drat-trim commit:

https://github.com/Udopia/candy-kingdom/tree/9bf617b3f090af7f0e5b80548690af0a8b5b7149/lib

If you follow it, you get:

https://github.com/Udopia/drat-trim/tree/d11f115f01c00cc6aa3d079a105748827905c8b2

Which is a 404

**Comment by eidelmanjonathan** [comment]
This is not related to our example, this is part of Hordesat. Please build Hordesat within the Dockerfile (and not on your machine) and this should work

**Comment by msoos** [comment]
So if I understand correctly, what you are saying is that the build scripts should not be there because they don't work? Why not remove them then, to thwart others from making the same mistake?

**Comment by eidelmanjonathan** [comment]
Well we included Hordesat as a submodule so people could see the code we were running, but you're right it's misleading. I have removed that submodule since it is not needed for the example
