### ISSUE TITLE
The system only extracts `.xz` files but the example AWS SAT infrastructure contains `bz2` files

### ISSUE THREAD

**Issue by msoos** [aws-samples/aws-batch-hordesat-sample#12]
This part of the code:

```
if [[ "${COMP_S3_PROBLEM_PATH}" == *".xz" ]];
then
  aws s3 cp s3://${S3_BKT}/${COMP_S3_PROBLEM_PATH} test.cnf.xz
  unxz test.cnf.xz
else
  aws s3 cp s3://${S3_BKT}/${COMP_S3_PROBLEM_PATH} test.cnf
fi
```
deals with `.xz` files only.  However, the S3 bucket here: https://s3.console.aws.amazon.com/s3/buckets/sat-comp-2020 contains `bz2` files. What's more strange is that `.gz` is what's more often used in SAT competitions, thanks to ZLIB being included in most SAT solvers. Perhaps the code could be improved to match what's in the bucket.

**Comment by eidelmanjonathan** [comment]
For the SMT competition, the examples will not be compressed so you do not have to include these lines in your submission
