### ISSUE TITLE
The final mpirun command seems not to be passing the right core number

### ISSUE THREAD

**Issue by msoos** [aws-samples/aws-batch-hordesat-sample#13]
This code doesn't seem to make sense to me:`time mpirun --mca btl_tcp_if_include eth0 --allow-run-as-root -np ${AWS_BATCH_JOB_NUM_NODES} --hostfile combined_hostfile /hordesat/hordesat  -c=${NUM_PROCESSES} -t=28800 -d=7 test.cnf`

In particular, `-c=${NUM_PROCESSES}` is a bit weird. This option, `-c` is supposed to set the number of cores used by the binary. However, `NUM_PROCESSES` is in `run-worker.sh` set to:
```
            \"name\":\"NUM_PROCESSES\",
            \"value\": \"$7\"
```

which in turn is set to `'2'` in run_example.py: `output2 = subprocess.check_output(['./run-worker.sh', args.profile, CLUSTER_NAME, stack_outputs["SolverProjectDefinition"], stack_outputs["Subnet"], stack_outputs["SecurityGroupId"], args.file, '2', ip_addr, args.project_name])`

But the README recommends using m4.4xlarge that has: `m4.4xlarge: 64 GiB of memory, 16 vCPUs, EBS-only, 64-bit platform` as per https://www.amazonaws.cn/en/ec2/instance-types/ so it ought to be set to 16, not 2?

**Comment by eidelmanjonathan** [comment]
Hello,

Thank you for pointing this out! Yes this is an old environment variable that people ended up not using in the competition. We will be running on m4.4xlarge instances as you say so you will have 16vcpus. I will remove this part from the example
